name: Client Beta Integration

on:
  push:
    branches:
      - '*beta'
      - '!master'
  pull_request:
    branches:
      - '*beta'
      - '!master'

jobs:
  build:
    # build sources with beta flags
    name: Client beta build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: gcc make
        run: make TYPE=beta
      - name: gcc examples
        run: make TYPE=beta examples

      - name: clean examples
        run: make clean-examples

      - name: g++ examples
        run: make TYPE=beta CC=g++ examples

      - name: Archive Shared Library
        uses: actions/upload-artifact@v2
        with:
          name: client-lib
          path: ./bin/libclient.so
          retention-days: 1
  
  test:
    # run tests with generated lib
    name: Client beta tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Shared Library
        uses: actions/download-artifact@v2
        with:
          name: client-lib
          path: ./bin

      - name: gcc tests
        run: make test
      - name: gcc run tests
        run: bash test/run.sh

      - name: clean tests
        run: make clean-tests

      - name: g++ tests
        run: make CC=g++ test
      - name: g++ run tests
        run: bash test/run.sh
