name: Client Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Client test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gcc make
        run: make
      - name: gcc examples
        run: make examples
      - name: clean
        run: make clean
      - name: g++ make
        run: make CC=g++
      - name: g++ examples
        run: make CC=g++ examples
